APP_SITE_URL= http://localhost:8080
file.upload-dir=${user.dir}/uploads/images
spring.application.name=${SPRING_APPLICATION_NAME:QLTTNgoaiNgu}

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${DATASOURCE_DRIVER_CLASS_NAME}

spring.jpa.hibernate.ddl-auto=${JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${JPA_SHOW_SQL}
spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT}

app.jwtSecret=${APP_JWT_SECRET}
app.jwtExpirationMs=${APP_JWT_EXPIRATION_MS}
app.jwtRefreshExpirationMs=${APP_JWT_REFRESH_EXPIRATION_MS}
app.jwt.token-prefix=${APP_JWT_TOKEN_PREFIX}
app.jwt.header=${APP_JWT_HEADER}

spring.liquibase.change-log=${LIQUIBASE_CHANGELOG}
spring.liquibase.enabled=${LIQUIBASE_ENABLED:true}


# Spring Mail
# C?u hình Gmail (Có fallback default value ?? tránh l?i build GitHub)
spring.mail.host=${GMAIL_SMTP_HOST:smtp.gmail.com}
spring.mail.port=${GMAIL_SMTP_PORT:587}
spring.mail.username=${GMAIL_USERNAME:nguyenbro9721@gmail.com}
spring.mail.password=${GMAIL_PASSWORD:fake-password-for-build}

# Các c?u hình SMTP m? r?ng
spring.mail.properties.mail.smtp.auth=${GMAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${GMAIL_SMTP_STARTTLS_ENABLE:true}
spring.mail.properties.mail.smtp.starttls.required=${GMAIL_SMTP_STARTTLS_REQUIRED:true}


lang=vi

# VNPay test environment (Sandbox)
# TMN Code vÃ  Hash Secret tá»« VNPay Sandbox
vnpay.tmn-code=8FHCECWU
vnpay.hash-secret=Y5CH2TNSOR0VLOJ9I2QPHNHYF1ZKS0M6
vnpay.api-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:8080/payment/vnpay-return
vnpay.frontend-redirect-url=http://localhost:3000/payment/result
vnpay.version=2.1.0
vnpay.command=pay
vnpay.order-type=other
vnpay.locale=vn
vnpay.currency-code=VND
vnpay.timezone=Asia/Ho_Chi_Minh
